apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      containers:
        - name: attendance-service
          image: deletus/attendance:F
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/ums-db
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  selector:
    app: attendance-service
  ports:
    - port: 80
      targetPort: 5000
