name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v2
      with:
        version: 'v1.24.0'

    - name: Set up kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Set up Docker for Kubernetes
      uses: docker/setup-buildx-action@v2

    - name: Deploy MongoDB
      run: kubectl apply -f k8s/mongodb-deployment.yaml

    - name: Deploy Faculty Service
      run: kubectl apply -f k8s/faculty-deployment.yaml

    - name: Deploy Student Service
      run: kubectl apply -f k8s/student-deployment.yaml

    - name: Deploy Schedule Service
      run: kubectl apply -f k8s/schedule-deployment.yaml

    - name: Deploy Attendance Service
      run: kubectl apply -f k8s/attendance-deployment.yaml

    - name: Apply Ingress (Optional)
      run: kubectl apply -f k8s/ingress.yaml

    - name: Check Kubernetes Deployment
      run: kubectl get pods && kubectl get services && kubectl get deployments
